kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: betterdev
  namespace: yeo
  labels:
    app: betterdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betterdev
  template:
    metadata:
      labels:
        app: betterdev
        name: betterdev
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: yeospace/betterdev
        imagePullPolicy: Always
        name: betterdev
        ports:
        - containerPort: 1605
        env:
          - name: MONGO_URI
            value: "mongodb://yeo.mongodb:27017"
          - name: AWS_REGION
            value: us-west-2
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: betterdev
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: betterdev
                key: AWS_SECRET_ACCESS_KEY


